/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  coy,
  coldarkDark,
  nightOwl,
  materialLight,
  materialDark,
  oneLight,
  oneDark,
  twilight,
  solarizedlight,
  coldarkCold,
  gruvboxDark,
  solarizedDarkAtom,
  prism,
  nord,
  lucario,
  coyWithoutShadows,
  cb,
} from 'react-syntax-highlighter/dist/esm/styles/prism';

export const themes: any = {
  coldarkDark,
  nightOwl,
  materialDark,
  gruvboxDark,
  cb,
  materialLight,
  oneLight,
  oneDark,
  coy,
  nord,
  solarizedlight,
  coldarkCold,
  solarizedDarkAtom,
  prism,
  lucario,
  coyWithoutShadows,
  twilight,
};
